-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#19120c",
	base01 = "#130d07",
	base02 = "#211a14",
	base03 = "#51453a",
	base04 = "#d5c3b5",
	base05 = "#efe0d5",
	base06 = "#372f28",
	base07 = "#403830",

	base08 = "#ffb4ab",
	base09 = "#c0cc9a",
	base0A = "#e1c1a4",
	base0B = "#fdb975",
	base0C = "#414b24",
	base0D = "#693c00",
	base0E = "#59422c",
	base0F = "#93000a",
})

local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

vim.api.nvim_set_hl(0, "Visual", {
	bg = "#693c00",
	fg = "#19120c",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#dce8b4",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#c0cc9a",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#e1c1a4",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#865318",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#130d07",
	fg = "#fdb975",
})
